name: PlatformIO CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs:
          [
            esp32dev_async_discovery,
            esp32s3_async_discovery,
            esp32dev_discovery,
            esp32s3_discovery
          ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update PIP cache on every commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: pip # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Update PlatformIO cache on every commit
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: platformio-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: platformio # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Update Build cache on every commit
        uses: actions/cache@v4
        with:
          path: .pio/
          key: build-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: build # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Update NodeJS cache on every commit
        uses: actions/cache@v4
        with:
          path: node_modules/
          key: node_modules-${{ github.run_id }}
          restore-keys: node_modules # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#

      - name: Update generated-files cache on every commit
        uses: actions/cache@v4
        with:
          path: |
            .pio/build/${{ matrix.envs }}/firmware.bin
            .pio/build/${{ matrix.envs }}/partitions.bin
            .pio/build/${{ matrix.envs }}/bootloader.bin
            .pio/build/${{ matrix.envs }}/littlefs.bin
          key: generated-files-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: generated-files # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Clean old build files
        run: pio run --target clean -e ${{ matrix.envs }}

      - name: Build Firmware
        run: pio run -e ${{ matrix.envs }}
